name: Kazoo Awesome Packaging Test

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  package-without-publish:
    name: Testing packaging WITHOUT publishing to Pypi
    runs-on: ubuntu-latest
    steps:
    - name: Handle the code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        -C--global-option=egg_info
        -C--global-option=--tag-build=""
        --sdist
        --wheel
        --outdir dist/
        .
